language: node_js

notifications:
  email: false
  
cache: npm

node_js:
  - 10.15.3
  - 8.9.0

before_script:
    ## Spin up container
  - cd test/docker/
  - docker-compose -f docker-compose.test.yml up -d

  ## Test for liveness
  # - docker exec -it gitlab bash -lc 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost/-/readiness)" != "200" ]]; do sleep 5; done'
  - sleep 240

  - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"')
  - export GITLAB_URL=$(docker exec -it gitlab bash -lc 'printf "%q" "${GITLAB_URL}"')
  - echo $GITLAB_URL
  - echo $PERSONAL_ACCESS_TOKEN

script:
  - npm run lint
  - npm run build
  - npm test:unit
  - npm run test:integration

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      node_js: 10.15.3
